language: scala
jdk: oraclejdk8
script: project/travis.sh

# Build only master and version tags - http://stackoverflow.com/a/31882307/463761
branches:
  only:
    - master
    - /^v[0-9]/

env:
  matrix:
    - TRAVIS_SBT_VERSION=0.13.x
    - TRAVIS_SBT_VERSION=1.x
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never
